/**
 * Build-time environment injection script.
 *
 * Reads the API_URL environment variable and writes it into
 * src/environments/environment.prod.ts before `ng build` runs.
 * This keeps the production API origin out of source control while
 * still using Angular's compile-time file-replacement mechanism.
 *
 * Usage (called automatically by `npm run build:render`):
 *   API_URL=https://api.bynder.com node scripts/set-env.mjs
 */

import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../src/environments/environment.prod.ts');

const apiUrl = process.env['API_URL'] ?? '';

if (!apiUrl) {
  console.warn(
    '\n[set-env] WARNING: API_URL is not set. ' +
    'API calls will fail in this build.\n' +
    'Set API_URL to your deployed backend origin (e.g. https://bynder-api.onrender.com) ' +
    'and redeploy.\n'
  );
}

mkdirSync(resolve(__dirname, '../src/environments'), { recursive: true });

writeFileSync(outPath, `// Auto-generated by scripts/set-env.mjs — do not edit manually.
// Set the API_URL environment variable in your hosting platform to control this value.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`);

console.log(\`[set-env] Wrote environment.prod.ts  →  apiUrl: "${apiUrl}"\`);
